Don't threat warnings as errors
Don't threat warnings as errors. This breaks compilation with Erlang 20
because of gen_fsm deprecation:

src/riak_kv_exchange_fsm.erl:61: gen_fsm:start/3 is deprecated and will be removed in a future release; use gen_statem:start/3
src/riak_kv_exchange_fsm.erl:79: gen_fsm:send_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/2
src/riak_kv_exchange_fsm.erl:118: gen_fsm:send_event_after/2 is deprecated and will be removed in a future release; use erlang:send_after/3
src/riak_kv_exchange_fsm.erl:132: gen_fsm:cancel_timer/1 is deprecated and will be removed in a future release; use erlang:cancel_timer/1
src/riak_kv_exchange_fsm.erl:137: gen_fsm:cancel_timer/1 is deprecated and will be removed in a future release; use erlang:cancel_timer/1
src/riak_kv_exchange_fsm.erl:334: gen_fsm:send_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/2
Compiling src/riak_kv_exchange_fsm.erl failed:
DEBUG: Worker compilation failed: {{error,
                                    {error,[],
                                     [["src/riak_kv_exchange_fsm.erl:61: gen_fsm:start/3 is deprecated and will be removed in a future release; use gen_statem:start/3\n",
                                       "src/riak_kv_exchange_fsm.erl:79: gen_fsm:send_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/2\n",
                                       "src/riak_kv_exchange_fsm.erl:118: gen_fsm:send_event_after/2 is deprecated and will be removed in a future release; use erlang:send_after/3\n",
                                       "src/riak_kv_exchange_fsm.erl:132: gen_fsm:cancel_timer/1 is deprecated and will be removed in a future release; use erlang:cancel_timer/1\n",
                                       "src/riak_kv_exchange_fsm.erl:137: gen_fsm:cancel_timer/1 is deprecated and will be removed in a future release; use erlang:cancel_timer/1\n",
                                       "src/riak_kv_exchange_fsm.erl:334: gen_fsm:send_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/2\n"]]}},
                                   {source,"src/riak_kv_exchange_fsm.erl"}}
ERROR: compile failed while processing /builddir/build/BUILD/riak_kv-2.1.8: rebar_abort

Signed-off-by: Peter Lemenkov <lemenkov@gmail.com>